"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME = 'VTA'
APP = ['main.py']
DATA_FILES = []
OPTIONS = {
    'packages': ['altgraph',
                 'certifi',
                 'decorator',
                 'idna',
                 'imageio',
                 'macholib',
                 'modulegraph',
                 'moviepy',
                 'numpy',
                 'proglog',
                 'py2app',
                 'PyQt5',
                 'pytube',
                 'requests',
                 'tqdm',
                 'urllib3',
                 'funcs',
                 'charset_normalizer'
                 ],
    'iconfile': 'icon.icns',
    'argv_emulation': False
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
